export default function replaceStr(str) {
  return str
    .replace(/无弹窗小说网/g, "")
    .replace(/www.530p.com/ig, "")
    .replace(/DouLaidu/ig, "")
    .replace(/www/ig, "")
    .replace(/com/ig, "")
    .replace(/txtxiazai/ig, "")
    .replace(/org/ig, "")
    .replace(/小说网最新章节阅读/ig, "")
    .replace(/ＷＷＷ。ＹＡＮＭＯＸＵＡＮ。ＯＲＧ/ig, "")
    .replace(/ｗｗｗ．２ｓｈｕｗｕ．ｃｏｍ/ig, "")
    .replace(/c66c/ig, "")
    .replace(/souDU/ig, "")
    .replace(/ｗｗｗ．Ｄｏｕｌａｉｄｕ．ｃｏｍ/ig, "")
    .replace(/XｇUANＣ◎/ig, "")
    .replace(/ｂｏｏｋ．ｚｈｕｉｋｅ．ｎｅｔ/ig, "")
    .replace(/看小说就到小说网/ig, "")
    .replace(/无弹窗广告小说网/ig, "")
    .replace(/看小说就到小说网/ig, "")
    .replace(/看小说就到小说网/ig, "")
    .replace(/看小说就到小说网/ig, "")
}
